### ISSUE TITLE
[Design] 기본 TextField UI를 구현합니다

### ISSUE THREAD

**Issue by Rookie0031** [extreme-rock/GetARock-iOS#24]
## 💡 Issue

여러 뷰에서 사용되는 기본 텍스트 필드를 구현합니다.

#### 기본 텍스트 필드
 중복 검사 버튼이 없는 기본 텍스트 필드입니다.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/103009135/213630422-60bc3dfa-39ed-4960-ae82-a8614f59288e.png">

## 📝  todo
- [x] 기본 텍스트 필드 기본 UI 구현

**Comment by compuTasha** [comment]
현재 이슈에는 기본 텍스트 필드만 다루는 게 맞나요??
todo에 중복확인 버튼 추가, 로직 추가 와 같은 고유값 텍스트 필드 구현의 todo에 해당되는 내용이 포함되어 있어 질문 남깁니다!

@Rookie0031

**Comment by Rookie0031** [comment]
아 원래는 기본 텍스트 필드에 중복 체크 여부 버튼 활성화 여부를 선택할 수 있게 만드려고했는데 글자수 제한 텍스트 필드는 따로 만들어서 PR을 올리려고 합니다!
이유는 
1. 한글 글자수 제한은 글자수 조절이 생각보다 까다로워서 로직이 좀 길어지다보니 기본 텍스트 필드를 그냥 따로 만드는 게 났다고 판단하였습니다,,
2. 중복 체크 버튼에 그라데이션이 들어가는데 노엘의 그라데이션 컬러 추가 작업 이후 그라데이션을 적용하기 위함이고 구엘의 Test용 API를 좀 더 적용해보기 위함입니다!!

<img width="500" alt="image" src="https://user-images.githubusercontent.com/103009135/214068314-802d26f4-f3d5-4ce8-9603-86bed56fdbe5.png">

꼼꼼한 체크 감사합니다 이번 이슈는 기본 텍스트 필드만 다루는거로 수정하고 글자수 제한 텍스트 필드는 새로 이슈를 파는게 나을까요??

**Comment by compuTasha** [comment]
설명 감사합니다!!

이번 이슈와 남은 태스크가 design(UI 구현) / feat(중복 체크 로직) 으로 크게 나뉘기도 하고,
중복 체크 로직도 사이즈가 커질 것 같아서 새로 이슈로 파는 게 좋을 것 같아요!
